Refactor to use events

diff --git a/dk b/dk
--- a/dk
+++ b/dk
@@ -27,49 +27,47 @@ realpath.dirname()  { if [[ $1 =~ /+[^/]+/*$ ]]; then REPLY="${1%${BASH_REMATCH}
 realpath.basename() { if [[ $1 =~ /*([^/]+)/*$ ]]; then REPLY="${BASH_REMATCH[1]}"; else REPLY=/; fi }
 
 realpath.follow() {
-    local target
-    while [[ -L "$1" ]] && target=$(readlink -- "$1"); do
-        realpath.dirname "$1"
-        # Resolve symlink target relative to symlink's directory
-        [[ $REPLY != . && $target != /* ]] && REPLY=$REPLY/$target || REPLY=$target
-        # Break out if we found a symlink loop
-        for target; do [[ $REPLY == "$target" ]] && break 2; done
-        # Add current result to the loop-detect list and tail-recurse
-        set -- "$REPLY" "$@"
-    done
-    REPLY="$1"
+	local target
+	while [[ -L "$1" ]] && target=$(readlink -- "$1"); do
+		realpath.dirname "$1"
+		# Resolve symlink target relative to symlink's directory
+		[[ $REPLY != . && $target != /* ]] && REPLY=$REPLY/$target || REPLY=$target
+		# Break out if we found a symlink loop
+		for target; do [[ $REPLY == "$target" ]] && break 2; done
+		# Add current result to the loop-detect list and tail-recurse
+		set -- "$REPLY" "$@"
+	done
+	REPLY="$1"
 }
 
 realpath.absolute() {
-    REPLY=$PWD; local no_eg; shopt -q extglob || { no_eg=y; shopt -s extglob; }
-    while (($#)); do case $1 in
-        /*) REPLY=/; set -- "${1##+(/)}" "${@:2}" ;;
-        */*) set -- "${1%%/*}" "${1##${1%%/*}+(/)}" "${@:2}" ;;
-        ''|.) shift ;;
-        ..) realpath.dirname "$REPLY"; shift ;;
-        *) REPLY="${REPLY%/}/$1"; shift ;;
-    esac; done; ${no_eg:+shopt -u extglob}
+	REPLY=$PWD; local no_eg; shopt -q extglob || { no_eg=y; shopt -s extglob; }
+	while (($#)); do case $1 in
+		/*) REPLY=/; set -- "${1##+(/)}" "${@:2}" ;;
+		*/*) set -- "${1%%/*}" "${1##${1%%/*}+(/)}" "${@:2}" ;;
+		''|.) shift ;;
+		..) realpath.dirname "$REPLY"; shift ;;
+		*) REPLY="${REPLY%/}/$1"; shift ;;
+	esac; done; ${no_eg:+shopt -u extglob}
 }
 
 realpath.canonical() {
-    local target=""
-    realpath.follow "$1"; set -- "$REPLY"   # $1 is now resolved
-    realpath.basename "$1"; target=$REPLY   # target = basename $1
-    realpath.dirname "$1";
-    [[ $REPLY != "$1" ]] && realpath.canonical "$REPLY"; # recurse unless root
-    realpath.absolute "$REPLY" "$target";   # combine canon parent w/basename
+	realpath.follow "$1"; set -- "$REPLY"   # $1 is now resolved
+	realpath.basename "$1"; set -- "$1" "$REPLY"   # $2 = basename $1
+	realpath.dirname "$1"
+	[[ $REPLY != "$1" ]] && realpath.canonical "$REPLY"; # recurse unless root
+	realpath.absolute "$REPLY" "$2";   # combine canon parent w/basename
 }
 
 realpath.relative() {
-    local target=""
-    realpath.absolute "$1"; set -- "$REPLY" "${@:2}"; realpath.absolute "${2-$PWD}" X
-    while realpath.dirname "$REPLY"; [[ "$1" != "$REPLY" && "$1" == "${1#${REPLY%/}/}" ]]; do
-        target=../$target
-    done
-    [[ $1 == "$REPLY" ]] && REPLY=${target%/} || REPLY="$target${1#${REPLY%/}/}"
-    REPLY=${REPLY:-.}
+	local target=""
+	realpath.absolute "$1"; set -- "$REPLY" "${@:2}"; realpath.absolute "${2-$PWD}" X
+	while realpath.dirname "$REPLY"; [[ "$1" != "$REPLY" && "$1" == "${1#${REPLY%/}/}" ]]; do
+		target=../$target
+	done
+	[[ $1 == "$REPLY" ]] && REPLY=${target%/} || REPLY="$target${1#${REPLY%/}/}"
+	REPLY=${REPLY:-.}
 }
-
 # For documentation, see https://github.com/bashup/loco
 
 set -euo pipefail
@@ -163,22 +161,69 @@ done
 for lv in ${!LOCO_@}; do unset $lv; done
 
 LOCO_SCRIPT=$0
-dk.bootstrap() { :; }
-dk.setup()     { dk bootstrap; }
-dk.update()    { dk bootstrap; }
-dk.cibuild()   { dk test; }
-dk.clean()     {
-    [[ "$BASHER_PREFIX" == "$PWD/.deps" ]] && rm -rf "$BASHER_PREFIX"
-    hash -r; linkbin .devkit/dk
+#!/usr/bin/env bash
+event() {
+	case $1 in valid|quote|error|once);;
+	*) local e=${2-} f n m=; e=${e%/*}; __ev.valid "$e"||m="Invalid event name '$e'"
+		case $1$m in on|off|has)
+			(($#>2))||m="${2-}: missing callback"; n=${2#$e} n=${n#/}
+			case $n in _)n='$#';;*) n=$((n));; esac
+			case $1${m:+_} in has_)m=;REPLY=;;*) __ev.quote "${@:3}";REPLY+=' "${@:2:'"$n"$'}"\n';; esac
+		esac
+		e=bashup_event_$e f=${e/event/flag}; ! [[ $m ]]||__ev.error "$m"||return
+	esac
+	__ev."$@"
 }
+__ev.error(){ echo "$1">&2;return ${2:-64};}
+__ev.valid(){ [[ ${1-} =~ ^[_[:alnum:]]+$ ]];}
+__ev.quote(){ REPLY=""; printf -v REPLY "${@+ %q}" "${@-}"; REPLY=${REPLY# };}
+__ev.has(){ [[ ${!e-} && $'\n'"${!e}" == *$'\n'"$REPLY"* && ! ${!f-} ]];}
+__ev.on(){ __ev.has && return;[[ ! ${!f-} ]]&&eval $e+='$REPLY'||eval "${!e-};$REPLY";}
+__ev.off(){ __ev.has||return 0; n="${!e}"; n=${n#"$REPLY"}; eval $e=$'"${n//\n"$REPLY"/\n}"';}
+__ev.emit(){ ${!f-};eval "${!e-}";}
+__ev.fire(){ ${!f-};set -- "$e" "${@:2}"; while [[ ${!1-} ]];do eval "$1=;${!1}"; done ;}
+__ev.all(){ ${!f-};e=${!e-};eval "${e//$'\n'/||return; }";}
+__ev.any(){ ${!f-};e=${!e-};eval "${e//$'\n'/&&return|| } ! :";}
+__ev.resolve(){
+	${!f-};__ev.fire "$@";__ev.quote "$@"
+	readonly $f="eval __ev.error 'event \"'$1'\" already resolved' 70;return" $e="set -- $REPLY"
+}
+__ev.resolved(){ [[ ${!f-} ]];}
+__ev.once(){ event on "${1%/*}" event off "$@" && event on "$@";}
+on() { event on "$@"; }
+before() { event on "before_$@"; }
+after()  { event on "after_$@"; }
+emit() { event emit "$@"; }
+run() { emit "before_$@"; emit "$@"; emit "after_$@"; }
+command-event() { event has "$1" || undefined-command "$1"; run "$@"; }
 
-dk.server()  { undefined-command server; }
-dk.test()    { undefined-command test; }
-dk.console() { undefined-command console; }
+dk.bootstrap() { event fire "boot"; }  # only run bootstrap callbacks once, can be no-op
+
+# default commands
+for REPLY in setup update build cibuild server test console clean; do
+    eval "dk.$REPLY() { command-event $REPLY \"\$@\"; }"
+    event once "before_$REPLY" dk bootstrap    # start everything with bootstrap
+done
+
+# Setup and update are ok as no-ops
+on "setup"  :
+on "update" :
+
+# Test before build and cibuild
+before "cibuild" dk test
+before "build"   dk test
+
+# Cleanup
+clean_deps() { [[ "$BASHER_PREFIX" == "$PWD/.deps" ]] && rm -rf "$BASHER_PREFIX"; }
+
+on    "clean" clean_deps
+after "clean" hash -r
+after "clean" linkbin .devkit/dk
 
 undefined-command() {
     abort "This project does not have a $1 command defined." 69   # EX_UNAVAILABLE
 }
+
 abort()    { log "$1"; exit $2; }
 log()      { echo "$1" >&2; }
 basher() {
@@ -271,4 +316,4 @@ loco_loadproject() {
 }
 loco_site_config() { :; }
 loco_user_config() { :; }
-if [[ $0 == "$BASH_SOURCE" ]]; then loco_main "$@"; fi
+if [[ $0 == "${BASH_SOURCE-}" ]]; then loco_main "$@"; fi
